DROP TABLE fornecedor;
CREATE TABLE fornecedor (id BIGINT NOT NULL, cnpj CHARACTER VARYING(255), nome CHARACTER VARYING(255), PRIMARY KEY (id));
DROP TABLE nota;
CREATE TABLE nota (id BIGINT NOT NULL, dataregistro TIMESTAMP(6) WITHOUT TIME ZONE, situacao INTEGER, PRIMARY KEY (id));
DROP TABLE notalancamento;
CREATE TABLE notalancamento (datalancamento DATE, data TIMESTAMP(6) WITHOUT TIME ZONE, numero CHARACTER VARYING(255), uf CHARACTER VARYING(255), id BIGINT NOT NULL, fornecedor_id BIGINT, PRIMARY KEY (id));
DROP TABLE notamovimento;
CREATE TABLE notamovimento (ano INTEGER, mes INTEGER, id BIGINT NOT NULL, PRIMARY KEY (id));
DROP TABLE notamovimento_movimentos;
CREATE TABLE notamovimento_movimentos (notamovimento_id BIGINT NOT NULL, entradafinanceira NUMERIC(19,2), entradafisica INTEGER, planodeconta_codigo CHARACTER VARYING(255));
DROP TABLE patrimonio;
CREATE TABLE patrimonio (orgao CHARACTER VARYING(255) NOT NULL, registro BIGINT NOT NULL, descricao CHARACTER VARYING(255), situacao CHARACTER VARYING(255), valoraquisicao NUMERIC(19,2), planodeconta_codigo CHARACTER VARYING(255), notalancamento_id BIGINT, PRIMARY KEY (orgao, registro));
DROP TABLE patrimonio_garantias;
CREATE TABLE patrimonio_garantias (patrimonio_orgao CHARACTER VARYING(255) NOT NULL, patrimonio_registro BIGINT NOT NULL, datainicio TIMESTAMP(6) WITHOUT TIME ZONE, duracaoemmeses BIGINT);
DROP TABLE planodeconta;
CREATE TABLE planodeconta (codigo CHARACTER VARYING(255) NOT NULL, descricao CHARACTER VARYING(255), PRIMARY KEY (codigo));
ALTER TABLE notalancamento ADD CONSTRAINT fk9ac56c2896e939dc FOREIGN KEY (fornecedor_id) REFERENCES fornecedor (id);
ALTER TABLE notalancamento ADD CONSTRAINT fk9ac56c28460194cb FOREIGN KEY (id) REFERENCES nota (id);
ALTER TABLE notamovimento ADD CONSTRAINT fkc81b23ae460194cb FOREIGN KEY (id) REFERENCES nota (id);
ALTER TABLE notamovimento_movimentos ADD CONSTRAINT fkf2b4508455c983a FOREIGN KEY (planodeconta_codigo) REFERENCES planodeconta (codigo);
ALTER TABLE notamovimento_movimentos ADD CONSTRAINT fkf2b4508da6a558 FOREIGN KEY (notamovimento_id) REFERENCES notamovimento (id);
ALTER TABLE patrimonio ADD CONSTRAINT fkded11b78455c983a FOREIGN KEY (planodeconta_codigo) REFERENCES planodeconta (codigo);
ALTER TABLE patrimonio ADD CONSTRAINT fkded11b78b15e721c FOREIGN KEY (notalancamento_id) REFERENCES notalancamento (id);
ALTER TABLE patrimonio_garantias ADD CONSTRAINT fk21f81e4e8e66f53f FOREIGN KEY (patrimonio_orgao, patrimonio_registro) REFERENCES patrimonio (orgao, registro);
